### ISSUE TITLE
Allow subsetting departure time window

### ISSUE THREAD

**Issue by abyrd** [conveyal/analyst-server#248]
If we do the our RAPTOR searches on a 2-hour time window, our current intermediate results format allows rendering results for any smaller time window falling within the original window.
​
Additional comments from @mattwigway :
We could potentially allow arbitrary time windows all day without much more information. Most of the size is in the paths, which scale less than linearly with additional minutes (because there is a fixed number of paths from A to B).​ We can also sample minutes, see a. owen’s work or even split the results up by time window (i.e. 8am-10am, 10am-12pm, 12pm-2pm, etc and just grab the ones needed for a particular analysis).

**Comment by mattwigway** [comment]
I think this should go in the browsochrones repository.
		
        
		--        Matthew Wigginton Conway       Transportation Analytics/Open SourceWashington, DCindicatrix.org
		 ---- On Tue, 17 Nov 2015 18:29:39 -0500  notifications@github.com  wrote ----If we do the our RAPTOR searches on a 2-hour time window, our current intermediate results format allows rendering results for any smaller time window falling within the original window.
​
Additional comments from @mattwigway :
We could potentially allow arbitrary time windows all day without much more information. Most of the size is in the paths, which scale less than linearly with additional minutes (because there is a fixed number of paths from A to B).​ We can also sample minutes, see a. owen’s work or even split the results up by time window (i.e. 8am-10am, 10am-12pm, 12pm-2pm, etc and just grab the ones needed for a particular analysis).

**Comment by abyrd** [comment]
It touches on the intermediate results format, the options in the client, and the final rendering of results from those intermediate results. Those things are scattered around in several repos at this point right? I'll move it over to browsochrones though.
