### ISSUE TITLE
administration of user credits/quotas

### ISSUE THREAD

**Issue by knaaptime** [conveyal/analyst-server#258]
Is there an administrative interface for modifying user origin credits? If so, how can it be accessed? If not, how can quotas be managed? 

I'm unable to perform any analyses, even though all the TA components are running, because I'm unable to distribute credits to users

**Comment by mattwigway** [comment]
Yes, there is an admin interface. In your stormpath configuration, create (or modify) a user so that they have "global admin" permissions, by adding `yourProjectPrefix_admin: true` to the user data (where `yourProjectPrefix` is the same as used for the project permissions in the user data). Log out and log in again, and you'll see a link to a ledger in the top bar that will let you administer credits.

**Comment by 3vivekb** [comment]
I think we should reopen this issue till somebody documents this.
